# Generated by Django 2.2.7 on 2019-12-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BcNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('newsurl', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'BcNews',
            },
        ),
        migrations.CreateModel(
            name='UserStates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('game', models.CharField(blank=True, max_length=100)),
                ('crawltime', models.CharField(max_length=50)),
                ('userurl', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'UserStates',
            },
        ),
    ]
